# Generated by Django 4.2.2 on 2023-06-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('website', models.CharField(max_length=200)),
                ('stuff_number', models.IntegerField()),
            ],
        ),
    ]
