# Generated by Django 4.2.2 on 2023-06-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_organization_is_nonprofit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
