# Generated by Django 4.2.2 on 2023-06-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_organization_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='organization',
            name='established_date',
            field=models.DateField(default=None),
        ),
    ]
