# Generated by Django 4.2.2 on 2023-06-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='stuff_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
