# Generated by Django 4.2.2 on 2023-06-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_organization_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_key', models.CharField(max_length=100)),
                ('server_id', models.CharField(max_length=150)),
                ('mac_address', models.CharField(max_length=200)),
                ('license_type', models.CharField(max_length=150)),
                ('license_expiry_date', models.DateField(default=True)),
                ('number_of_users', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization')),
            ],
        ),
    ]
