# Generated by Django 4.2.2 on 2023-06-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='number_of_users',
            field=models.IntegerField(),
        ),
    ]
