# Generated by Django 4.2.2 on 2023-06-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_license_number_of_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='action',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='license',
            name='number_of_users',
            field=models.IntegerField(default=0),
        ),
    ]
