# Generated by Django 4.2.2 on 2023-06-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_license_action_alter_license_number_of_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='action',
        ),
    ]
